package com.company.enums;

public enum Region {
    TASHKENT,
    BUKHARA,
    SAMARKAND,
    JIZZAKH,
    KHOREZM,
    FERGANA,
    NAVOIY,
    KASHKADARYA,
    SURKHANDARYA,
    RESPUBLIC_OF_KARAKALPAKISTAN,
    TASHKENT_REGION,
    NAMANGAN,
    ANDIJAN,
    SIRDARYA;
}
